GLOBAL_MAIN_PID="$$"

GLOBAL_STD_PROVIDERS_ROOT="$GLOBAL_PAG_ROOT/providers"

GLOBAL_STATE_ROOT="$HOME/.config/pag"
[ -d "$GLOBAL_STATE_ROOT" ] || mkdir -p "$GLOBAL_STATE_ROOT"

GLOBAL_REGISTRIES_ROOT="$GLOBAL_STATE_ROOT/registries"
[ -d "$GLOBAL_REGISTRIES_ROOT" ] || mkdir -p "$GLOBAL_REGISTRIES_ROOT"

GLOBAL_USER_PROVIDERS_ROOT="$GLOBAL_STATE_ROOT/providers"
[ -d "$GLOBAL_USER_PROVIDERS_ROOT" ] || mkdir -p "$GLOBAL_USER_PROVIDERS_ROOT"
